### ISSUE TITLE
Refresh on security policy reporting warning

### ISSUE THREAD

**Issue by nabheet** [pulumi/pulumi-gcp#3142]
### Describe what happened

Whenever I refresh a gcp.SecurityPolicy I get the following warnings:

```
Diagnostics:
  gcp:compute:SecurityPolicy (my-security-policy):
    warning: Failed to calculate preview for element in rules: interface conversion: interface {} is string, not bool
    warning: Failed to calculate preview for element in rules: interface conversion: interface {} is string, not bool
    warning: Failed to calculate preview for element in rules: interface conversion: interface {} is string, not bool
    warning: Failed to calculate preview for element in rules: interface conversion: interface {} is string, not bool
```

I don't see any bools in our configuration so I am not sure why this is happening.

### Sample program

```
compute.SecurityPolicy(
            f"{project_id}-security-policy",
            description="throttle access to cloud run services",
            adaptive_protection_config=compute.SecurityPolicyAdaptiveProtectionConfigArgs(
                layer7_ddos_defense_config=compute.SecurityPolicyAdaptiveProtectionConfigLayer7DdosDefenseConfigArgs(
                    enable=True,
                    rule_visibility="STANDARD",
                )
            ),
            advanced_options_config=compute.SecurityPolicyAdvancedOptionsConfigArgs(
                json_custom_config=compute.SecurityPolicyAdvancedOptionsConfigJsonCustomConfigArgs(
                    content_types=["application/json"],
                ),
                json_parsing="STANDARD",
            ),
            rules=rules + preconf_waf_configs,
            opts=ResourceOptions(
                depends_on=[services["compute"]],
            ),
        )
```

### Log output

```
Diagnostics:
  gcp:compute:SecurityPolicy (my-security-policy):
    warning: Failed to calculate preview for element in rules: interface conversion: interface {} is string, not bool
    warning: Failed to calculate preview for element in rules: interface conversion: interface {} is string, not bool
    warning: Failed to calculate preview for element in rules: interface conversion: interface {} is string, not bool
    warning: Failed to calculate preview for element in rules: interface conversion: interface {} is string, not bool
```

### Affected Resource(s)

gcp.SecurityPolicy

### Output of `pulumi about`

We are using Pulumi Python bindings.
```
CLI          
Version      3.158.0
Go Version   go1.24.1
Go Compiler  gc

Host     
OS       debian
Version  12.10
Arch     aarch64

Backend        
Name           pulumi.com
URL            https://app.pulumi.com
User           Unknown
Organizations  
Token type     personal
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Thanks for reporting @nabheet and sorry you hit this.

Do you have a sample program which reproduces this?

**Comment by nabheet** [comment]
This will take me some time to generate as our python code is generated in loops based on configuration. But I will keep updating slowly.

**Comment by VenelinMartinov** [comment]
Appreciate the repro @nabheet, this is related to some recent improvements we've made to the preview experience: https://github.com/pulumi/pulumi-terraform-bridge/issues/2598

Unfortunately it seems that you've hit a case we are not handling correctly.

**Comment by VenelinMartinov** [comment]
@nabheet can you please give some details about the contents of `rules` and `preconf_waf_configs`? I couldn't reproduce the issue with some rules I tried.

Can you also please confirm if the issue still happens with the newest GCP provider v8.26.1? We've released a fix for a very related issue, so I suspect this might be fixed too.

**Comment by nabheet** [comment]
I think this issue is fixed in the latest released version. The warning was displayed when I ran preview but for some reason it update the rules without preview. Now no warning is displayed.

**Comment by nabheet** [comment]
I am sorry it seems to be happening again.

```
 ~  gcp:compute:SecurityPolicy my-project-security-policy refreshing (0s) warning: Failed to calculate preview for element in rules: Failed to calculate set hash: interface conversion: interface {} is string, not bool
 ~  gcp:compute:SecurityPolicy my-project-security-policy refreshing (0s) warning: Failed to calculate preview for element in rules: Failed to calculate set hash: interface conversion: interface {} is string, not bool
 ~  gcp:compute:SecurityPolicy my-project-security-policy refreshing (0s) warning: Failed to calculate preview for element in rules: Failed to calculate set hash: interface conversion: interface {} is string, not bool
 ~  gcp:compute:SecurityPolicy my-project-security-policy updated (0.27s) [diff: ~rules]; warning: Failed to calculate preview for element in rules: Failed to calculate set hash: interface conversion: interface {} is string, not bool
```

I am going to get you a minimal code reproduction. And as the warning states, it is something in `rules` field. I need some time.

**Comment by nabheet** [comment]
Here is the Pulumi python package:
```
"pulumi-gcp": {
            "hashes": [
                "sha256:76804626e5933f5bbce491d9cd296da2cb334e37cd84bbb6510d7219a70e159f",
                "sha256:9c9fc6634208239ad602b7f78fd67319060cbafbdd327fd08df72a78056052a3"
            ],
            "index": "pypi",
            "markers": "python_version >= '3.9'",
            "version": "==8.27.0"
        },
```

Our code structure does not allow me to easily copy/paste it here. And same as you, if I create a small example to reproduce the issue, it does not produce this warning. Sorry this is taking me a while but I am working on a example for you whenever I have some downtime.

**Comment by nabheet** [comment]
Aite, here it goes. Hope this will help you reproduce the issue. Also, the issue only happens after the second time I refresh the state. It does not happen on the first refresh, which is probably why I missed it earlier.

```
        rules_config = {
            "print-pdf": {
                "action": "throttle",
                "priority": 2002,
                "rule_match_expr": "has(request.headers['user-agent']) && request.headers['user-agent'] == 'my-user-agent'",
                "rate_limit_threshold": {
                    "count": 5_000,
                    "interval_sec": 60,
                },
            },
            "everyone": {
                "action": "throttle",
                "priority": 2_147_483_647,
                "enforce-on-key-configs": [
                    {
                        "enforce-on-key-type": "IP",
                    },
                ],
                "src_ip_ranges": [
                    "*",
                ],
                "rate_limit_threshold": {
                    "count": 120,
                    "interval_sec": 60,
                },
            },
        }

        rules = []
        for key, value in rules_config.items():
            action = value["action"]
            match = None
            rate_limit_options = None
            src_ip_ranges = value.get("src_ip_ranges")
            enforce_on_key = "IP"

            enforce_on_key_configs = _configure_enforce_on_key(
                value.get("enforce-on-key-configs")
            )

            if enforce_on_key_configs:
                enforce_on_key = None

            if src_ip_ranges:
                match = compute.SecurityPolicyRuleMatchArgs(
                    versioned_expr="SRC_IPS_V1",
                    config=compute.SecurityPolicyRuleMatchConfigArgs(
                        src_ip_ranges=src_ip_ranges,
                    ),
                )
            else:
                match = compute.SecurityPolicyRuleMatchArgs(
                    expr=compute.SecurityPolicyRuleMatchExprArgs(
                        expression=value["rule_match_expr"],
                    )
                )

            if action == "throttle":
                rate_limit_options = compute.SecurityPolicyRuleRateLimitOptionsArgs(
                    rate_limit_threshold=compute.SecurityPolicyRuleRateLimitOptionsRateLimitThresholdArgs(
                        count=value["rate_limit_threshold"]["count"],
                        interval_sec=value["rate_limit_threshold"]["interval_sec"],
                    ),
                    conform_action="allow",
                    exceed_action="deny(429)",
                    enforce_on_key=enforce_on_key,
                    enforce_on_key_configs=enforce_on_key_configs,
                )

            rules.append(
                compute.SecurityPolicyRuleArgs(
                    description=f"{action} {key}",
                    action=action,
                    priority=value["priority"],
                    match=match,
                    rate_limit_options=rate_limit_options,
                ),
            )
        security_policy = compute.SecurityPolicy(
            f"{project_id}-security-policy",
            description="throttle access to cloud run services",
            adaptive_protection_config=compute.SecurityPolicyAdaptiveProtectionConfigArgs(
                layer7_ddos_defense_config=compute.SecurityPolicyAdaptiveProtectionConfigLayer7DdosDefenseConfigArgs(
                    enable=True,
                    rule_visibility="STANDARD",
                )
            ),
            advanced_options_config=compute.SecurityPolicyAdvancedOptionsConfigArgs(
                json_custom_config=compute.SecurityPolicyAdvancedOptionsConfigJsonCustomConfigArgs(
                    content_types=["application/json"],
                ),
                json_parsing="STANDARD",
            ),
            rules=rules,
            opts=ResourceOptions(
                depends_on=[services["compute"]],
            ),
        )
```

Output:

```
...
Diagnostics:
  gcp:compute:SecurityPolicy (funcfi-dev-nab-security-policy):
    warning: Failed to calculate preview for element in rules: Failed to calculate set hash: interface conversion: interface {} is string, not bool
    warning: Failed to calculate preview for element in rules: Failed to calculate set hash: interface conversion: interface {} is string, not bool
...
```

**Comment by nabheet** [comment]
Aite, here it goes. Hope this will help you reproduce the issue. Also, the issue only happens after the second time I refresh the state. It does not happen on the first refresh, which is probably why I missed it earlier.

```
        rules_config = {
            "my-service": {
                "action": "throttle",
                "priority": 2002,
                "rule_match_expr": "has(request.headers['user-agent']) && request.headers['user-agent'] == 'my-user-agent'",
                "rate_limit_threshold": {
                    "count": 5_000,
                    "interval_sec": 60,
                },
            },
            "everyone": {
                "action": "throttle",
                "priority": 2_147_483_647,
                "enforce-on-key-configs": [
                    {
                        "enforce-on-key-type": "IP",
                    },
                ],
                "src_ip_ranges": [
                    "*",
                ],
                "rate_limit_threshold": {
                    "count": 120,
                    "interval_sec": 60,
                },
            },
        }

        rules = []
        for key, value in rules_config.items():
            action = value["action"]
            match = None
            rate_limit_options = None
            src_ip_ranges = value.get("src_ip_ranges")
            enforce_on_key = "IP"

            enforce_on_key_configs = _configure_enforce_on_key(
                value.get("enforce-on-key-configs")
            )

            if enforce_on_key_configs:
                enforce_on_key = None

            if src_ip_ranges:
                match = compute.SecurityPolicyRuleMatchArgs(
                    versioned_expr="SRC_IPS_V1",
                    config=compute.SecurityPolicyRuleMatchConfigArgs(
                        src_ip_ranges=src_ip_ranges,
                    ),
                )
            else:
                match = compute.SecurityPolicyRuleMatchArgs(
                    expr=compute.SecurityPolicyRuleMatchExprArgs(
                        expression=value["rule_match_expr"],
                    )
                )

            if action == "throttle":
                rate_limit_options = compute.SecurityPolicyRuleRateLimitOptionsArgs(
                    rate_limit_threshold=compute.SecurityPolicyRuleRateLimitOptionsRateLimitThresholdArgs(
                        count=value["rate_limit_threshold"]["count"],
                        interval_sec=value["rate_limit_threshold"]["interval_sec"],
                    ),
                    conform_action="allow",
                    exceed_action="deny(429)",
                    enforce_on_key=enforce_on_key,
                    enforce_on_key_configs=enforce_on_key_configs,
                )

            rules.append(
                compute.SecurityPolicyRuleArgs(
                    description=f"{action} {key}",
                    action=action,
                    priority=value["priority"],
                    match=match,
                    rate_limit_options=rate_limit_options,
                ),
            )
        security_policy = compute.SecurityPolicy(
            f"{project_id}-security-policy",
            description="throttle access to cloud run services",
            adaptive_protection_config=compute.SecurityPolicyAdaptiveProtectionConfigArgs(
                layer7_ddos_defense_config=compute.SecurityPolicyAdaptiveProtectionConfigLayer7DdosDefenseConfigArgs(
                    enable=True,
                    rule_visibility="STANDARD",
                )
            ),
            advanced_options_config=compute.SecurityPolicyAdvancedOptionsConfigArgs(
                json_custom_config=compute.SecurityPolicyAdvancedOptionsConfigJsonCustomConfigArgs(
                    content_types=["application/json"],
                ),
                json_parsing="STANDARD",
            ),
            rules=rules,
            opts=ResourceOptions(
                depends_on=[services["compute"]],
            ),
        )
```

Output:

```
...
Diagnostics:
  gcp:compute:SecurityPolicy (my-project-security-policy):
    warning: Failed to calculate preview for element in rules: Failed to calculate set hash: interface conversion: interface {} is string, not bool
    warning: Failed to calculate preview for element in rules: Failed to calculate set hash: interface conversion: interface {} is string, not bool
...
```

**Comment by VenelinMartinov** [comment]
This was fixed in https://github.com/pulumi/pulumi-gcp/releases/tag/v8.29.0

**Comment by nabheet** [comment]
I am sorry I just upgraded both the binary and pulumi-gcp and this warning is still showing up.

```
$ pulumi version
v3.167.0
$ grep -A 8 "pulumi-gcp" Pipfile.lock
        "pulumi-gcp": {
            "hashes": [
                "sha256:4ad52bc24bdb3d1781856418c1ab41949cf4ec94d3e371a919c751ff9260b431",
                "sha256:fefe857587dbaba5dfd250779debe4f2c52b1e383186bcba3488db3862497bd1"
            ],
            "index": "pypi",
            "markers": "python_version >= '3.9'",
            "version": "==8.29.0"
        },
```

**Comment by VenelinMartinov** [comment]
@nabheet this does not reproduce for me on pulumi-gcp v8.29.0. I tried the program you posted above and ran the following:
1. pulumi up --yes
2. pulumi refresh --yes
3. pulumi refresh

I get no warning for the program.

Can you please post the output of `pulumi about` from you stack? Can you also help me reproduce the warning - it seems like the original repro you posted no longer produces the warning.

**Comment by nabheet** [comment]
I must have made some mistake running it after the upgrade. Using a cleaner set up I am no longer getting the warnings. I just ran it 5 times just to be sure.

Thank you for fixing this!

**Comment by VenelinMartinov** [comment]
Awesome @nabheet, great to hear, thanks for checking!
